version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  test-redis:
    image: redis:alpine
    ports:
      - "16379:6379"
